// Code generated by apigen. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/example/blog/internal/model"
	"github.com/example/blog/internal/service"
	"github.com/gin-gonic/gin"
)

// CommentHandler wires HTTP routes to the CommentService.
type CommentHandler struct {
	svc service.CommentService
}

// NewCommentHandler constructs a CommentHandler.
func NewCommentHandler(svc service.CommentService) *CommentHandler {
	return &CommentHandler{svc: svc}
}

// RegisterRoutes registers all Comment routes on the given router group.
func (h *CommentHandler) RegisterRoutes(r *gin.RouterGroup) {
	r.GET("/posts/:postId/comments", h.ListComments)
	r.POST("/posts/:postId/comments", h.CreateComment)
	r.DELETE("/posts/:postId/comments/:id", h.DeleteComment)
}

// ListComments handles GET /posts/:postId/comments.
func (h *CommentHandler) ListComments(c *gin.Context) {
	var req model.ListCommentsRequest
	if err := c.ShouldBindQuery(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}
	postId := c.Param("postId")
	result, err := h.svc.ListComments(c.Request.Context(), postId, req)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	c.JSON(http.StatusOK, result)
}

// CreateComment handles POST /posts/:postId/comments.
func (h *CommentHandler) CreateComment(c *gin.Context) {
	var req model.CreateCommentRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}
	postId := c.Param("postId")
	result, err := h.svc.CreateComment(c.Request.Context(), postId, req)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	c.JSON(http.StatusOK, result)
}

// DeleteComment handles DELETE /posts/:postId/comments/:id.
func (h *CommentHandler) DeleteComment(c *gin.Context) {
	postId := c.Param("postId")
	id := c.Param("id")
	result, err := h.svc.DeleteComment(c.Request.Context(), postId, id)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}
	c.JSON(http.StatusOK, result)
}
