// Code generated by apigen. DO NOT EDIT.
package service

import (
	"context"

	"github.com/example/blog/internal/model"
)

// CommentService defines business logic operations for Comment.
// Implement this interface in a separate (non-generated) file.
type CommentService interface {
	ListComments(ctx context.Context, postId string, req model.ListCommentsRequest) ([]model.Comment, error)
	CreateComment(ctx context.Context, postId string, req model.CreateCommentRequest) (model.Comment, error)
	DeleteComment(ctx context.Context, postId string, id string) (model.Comment, error)
}
