// Code generated by apigen. DO NOT EDIT.
package service

import (
	"context"

	"github.com/example/blog/internal/model"
)

// PostService defines business logic operations for Post.
// Implement this interface in a separate (non-generated) file.
type PostService interface {
	ListPosts(ctx context.Context, req model.ListPostsRequest) ([]model.Post, error)
	GetPost(ctx context.Context, id string) (model.Post, error)
	CreatePost(ctx context.Context, req model.CreatePostRequest) (model.Post, error)
	UpdatePost(ctx context.Context, req model.UpdatePostRequest, id string) (model.Post, error)
	DeletePost(ctx context.Context, id string) (model.Post, error)
}
