// Code generated by apigen. DO NOT EDIT.
package repository

import (
	"context"

	"github.com/example/blog/internal/model"
)

// PostRepository defines data-access operations for Post.
// Implement this interface in a separate (non-generated) file.
type PostRepository interface {
	ListPosts(ctx context.Context, req model.ListPostsRequest) ([]model.Post, error)
	GetPost(ctx context.Context, id string) (model.Post, error)
	CreatePost(ctx context.Context, req model.CreatePostRequest) (model.Post, error)
	UpdatePost(ctx context.Context, id string, req model.UpdatePostRequest) (model.Post, error)
	DeletePost(ctx context.Context, id string) (model.Post, error)
}
